# Standard libraries
import json
import os
import re
import asyncio
import random

# Load environment variables (.env)
from dotenv import load_dotenv

# Groq LLM client
from groq import Groq

# SPADE multi-agent framework
from spade.agent import Agent
from spade.behaviour import CyclicBehaviour
from spade.message import Message

# Google search utility (scraping-based)
from googlesearch import search

# Retry mechanism for robustness
from tenacity import retry, stop_after_attempt, wait_exponential

# Custom logging utility
from shared import log_message


# Load environment variables (e.g., GROQ_API_KEY)
load_dotenv()

# Initialize Groq client
client = Groq(api_key=os.getenv("GROQ_API_KEY"))


class ResourcerAgent(Agent):
    """
    Agent responsible for finding and refining learning resources
    (academic papers, videos, or code examples).
    """

    def __init__(self, jid, password, resource_type):
        """
        Parameters:
        - jid: agent identifier (XMPP)
        - password: authentication
        - resource_type: type of resources ('academic', 'media', 'code')
        """
        super().__init__(jid, password)
        self.resource_type = resource_type


    class ResourceBehaviour(CyclicBehaviour):
        """
        Behaviour that continuously:
        - receives tasks
        - searches for resources
        - refines results using AI
        - sends enriched tasks back
        """

        # Retry logic for AI cleaning step (robust against API failures)
        @retry(
            stop=stop_after_attempt(3),  # Retry up to 3 times
            wait=wait_exponential(multiplier=1, min=2, max=6)  # Backoff: 2s → 4s → max 6s
        )
        def clean_with_ai(self, search_data, topic):
            """
            Uses LLM to select the best link and format it as clean JSON.

            Parameters:
            - search_data (list): list of URLs from Google search
            - topic (str): task/topic name

            Returns:
            - str: JSON string generated by the model
            """

            # Strict prompt forcing valid JSON output
            prompt = f"""
                        Pick the 1 best link for '{topic}' from this data: {search_data}.
                        Return ONLY valid JSON using double quotes. Do not use single quotes.
                        Format exactly like this:
                        [
                          {{"name": "Clean Title", "url": "https://...", "type": "{self.agent.resource_type}"}}
                        ]
                        """

            # Call Groq API
            chat = client.chat.completions.create(
                messages=[{"role": "user", "content": prompt}],
                model="llama-3.1-8b-instant",  # Faster, cheaper model
                temperature=0.1,  # Very low randomness → more deterministic JSON
            )

            # Return raw model output
            return chat.choices[0].message.content


        async def run(self):
            """
            Main loop:
            - Wait for tasks
            - Search resources
            - Clean results via AI
            - Return structured data
            """

            # Wait for incoming message (timeout = 30s)
            msg = await self.receive(timeout=30)

            if msg and msg.body:
                try:
                    # Parse incoming JSON tasks
                    tasks = json.loads(msg.body)

                except json.JSONDecodeError:
                    # Ignore invalid messages
                    return

                # Log activity
                log_message(
                    f"[RESOURCER-{self.agent.resource_type.upper()}] Hunting resources..."
                )

                # Avoid being blocked by Google (anti-bot protection)
                await asyncio.sleep(random.uniform(0.5, 2.5))

                # Process each task
                for task in tasks:
                    try:
                        # Build search query based on resource type
                        if self.agent.resource_type == "academic":
                            query = f"site:arxiv.org OR site:edu {task['name']} paper pdf"

                        elif self.agent.resource_type == "media":
                            query = f"site:youtube.com {task['name']} tutorial lecture"

                        else:  # 'code'
                            query = f"site:github.com OR site:stackoverflow.com {task['name']} code example"

                        # Perform Google search (top 3 results)
                        raw_links = [url for url in search(query, num_results=3)]
                        
                        # --- THE FIX ---
                        # If Google blocked us and returned empty data, immediately trigger the fallback
                        if not raw_links:
                            raise ValueError("Google blocked the search (0 results returned).")
                        # ---------------

                        # Use AI to select best link and clean output
                        ai_resp = self.clean_with_ai(raw_links, task['name'])

                        # Extract JSON array from AI response using regex
                        match = re.search(r'\[.*\]', ai_resp, re.DOTALL)

                        if match:
                            # Parse cleaned JSON
                            task["resources"] = json.loads(match.group())

                        else:
                            # Because of our check above, we now know for sure that raw_links[0] exists!
                            task["resources"] = [{
                                "name": "Suggested Link",
                                "url": raw_links[0],
                                "type": self.agent.resource_type
                            }]

                    except Exception as e:
                        # Log error (trimmed for readability)
                        log_message(
                            f"[RESOURCER-{self.agent.resource_type.upper()}] "
                            f"Fallback triggered. Error: {str(e)[:40]}"
                        )

                        # Fallback: generic Google search link
                        fallback_url = (
                            f"https://www.google.com/search?q="
                            f"{task['name'].replace(' ', '+')}+{self.agent.resource_type}"
                        )

                        task["resources"] = [{
                            "name": f"Search for {self.agent.resource_type} resources",
                            "url": fallback_url,
                            "type": self.agent.resource_type
                        }]

                # Prepare reply message
                reply = Message(to=str(msg.sender))

                # Convert updated tasks to JSON
                reply.body = json.dumps(tasks)

                # Preserve conversation thread
                reply.thread = msg.thread

                # Send response
                await self.send(reply)


    async def setup(self):
        """
        Called when agent starts.
        Registers its behaviour.
        """
        self.add_behaviour(self.ResourceBehaviour())